# Generated by Django 4.2.9 on 2024-01-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=50)),
                ("text", models.TextField()),
                ("date", models.DateTimeField()),
                ("likes", models.IntegerField(default=0)),
                ("image", models.URLField(blank=True)),
            ],
        ),
    ]
